---
# tasks file for ansible-role-nexus3

- include: "install_{{ ansible_os_family }}.yml"

- include: "configure_{{ ansible_os_family }}.yml"

- name: Nexus Service
  service:
    name: nexus
    state: started
    enabled: yes
  become: yes
