---
# handlers file for ansible-role-nexus3

- name: Restart Nexus
  service:
    name: nexus
    state: restarted
  notify: Wait for Nexus
  become: yes

- name: Wait for Nexus
  uri:
    url: "http://localhost:{{ nexus3_http_port }}{{ nexus3_context_path | default('') }}"
    status_code: 200
  register: nexus3_top_page
  until: nexus3_top_page.status is not defined or nexus3_top_page.status == 200
  retries: 60
  delay: 1
